# Generated by Django 3.2.4 on 2021-07-15 02:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('grade', models.CharField(max_length=3)),
                ('average_at_risk', models.IntegerField(blank=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('date_of_birth', models.DateField()),
                ('grade', models.CharField(max_length=3)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('question_1', models.CharField(choices=[('Y', 'Correct Answer'), ('N', 'Incorrect Answer')], default='N', max_length=1)),
                ('question_2', models.CharField(choices=[('Y', 'Correct Answer'), ('N', 'Incorrect Answer')], default='N', max_length=1)),
                ('question_3', models.CharField(choices=[('Y', 'Correct Answer'), ('N', 'Incorrect Answer')], default='N', max_length=1)),
                ('question_4', models.CharField(choices=[('Y', 'Correct Answer'), ('N', 'Incorrect Answer')], default='N', max_length=1)),
                ('question_5', models.CharField(choices=[('Y', 'Correct Answer'), ('N', 'Incorrect Answer')], default='N', max_length=1)),
                ('question_6', models.CharField(choices=[('Y', 'Correct Answer'), ('N', 'Incorrect Answer')], default='N', max_length=1)),
                ('question_7', models.CharField(choices=[('Y', 'Correct Answer'), ('N', 'Incorrect Answer')], default='N', max_length=1)),
                ('question_8', models.CharField(choices=[('Y', 'Correct Answer'), ('N', 'Incorrect Answer')], default='N', max_length=1)),
                ('question_9', models.CharField(choices=[('Y', 'Correct Answer'), ('N', 'Incorrect Answer')], default='N', max_length=1)),
                ('question_10', models.CharField(choices=[('Y', 'Correct Answer'), ('N', 'Incorrect Answer')], default='N', max_length=1)),
                ('question_11', models.CharField(choices=[('Y', 'Correct Answer'), ('N', 'Incorrect Answer')], default='N', max_length=1)),
                ('question_12', models.CharField(choices=[('Y', 'Correct Answer'), ('N', 'Incorrect Answer')], default='N', max_length=1)),
                ('question_13', models.CharField(choices=[('Y', 'Correct Answer'), ('N', 'Incorrect Answer')], default='N', max_length=1)),
                ('question_14', models.CharField(choices=[('Y', 'Correct Answer'), ('N', 'Incorrect Answer')], default='N', max_length=1)),
                ('question_15', models.CharField(choices=[('Y', 'Correct Answer'), ('N', 'Incorrect Answer')], default='N', max_length=1)),
                ('question_16', models.CharField(choices=[('Y', 'Correct Answer'), ('N', 'Incorrect Answer')], default='N', max_length=1)),
                ('question_17', models.CharField(choices=[('Y', 'Correct Answer'), ('N', 'Incorrect Answer')], default='N', max_length=1)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_info.classroom')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
