# Generated by Django 3.2.4 on 2021-07-15 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='average_at_risk',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
