# Generated by Django 3.2.4 on 2021-07-15 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_info', '0003_auto_20210714_2332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='student',
            name='teacher',
        ),
    ]
